services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8500/v1/status/leader"]
      interval: 5s
      timeout: 3s
      retries: 20

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
      MYSQL_DATABASE: YOU_DB
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pYOU_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  # user:
  #   # image: app-user:dev
  #   build:
  #     context: .
  #     dockerfile: docker_files/DockerFile.user
  #   ports:
  #     - "8083:8080"
  #   environment:
  #     - GO_ENV=online
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=YOUR_PASSWORD
  #     - MYSQL_DATABASE=YOU_DB
  #     - MYSQL_HOST=mysql
  #   depends_on:
  #     consul:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
      

  # product:
  #   # image: app-product:dev
  #   build:
  #     context: .
  #     dockerfile: docker_files/DockerFile.product
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     - GO_ENV=online
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=YOUR_PASSWORD
  #     - MYSQL_DATABASE=YOU_DB
  #     - MYSQL_HOST=mysql
  #   depends_on:
  #     consul:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  # cart:
  #   # image: app-product:dev
  #   build:
  #     context: .
  #     dockerfile: docker_files/DockerFile.cart
  #   ports:
  #     - "8084:8080"
  #   environment:
  #     - GO_ENV=online
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=YOUR_PASSWORD
  #     - MYSQL_DATABASE=YOU_DB
  #     - MYSQL_HOST=mysql
  #   depends_on:
  #     consul:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

  # frontend:
  #   # image: app-frontend:dev
  #   build:
  #     context: .
  #     dockerfile: docker_files/DockerFile.frontend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - GO_ENV=online
  #     - SESSION_SECRET=YOUR_SESSION_SECRET
  #   depends_on:
  #     consul:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     user:
  #       condition: service_started
  #     product:
  #       condition: service_started
        

volumes:
  mysql_data:
